---
- hosts: all

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - dnsmasq-server