---
- hosts: all

  pre_tasks:
    - name: Update DNF cache
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts["os_family"] == "RedHat"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts["os_family"] == "Debian"
  
  roles:
    - sentinelone