---
- hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts["os_family"] == "Debian"
    
    - name: Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts["os_family"] == "RedHat"

    - name: Install yum-utils (RH)
      ansible.builtin.dnf:
        name: yum-utils
        state: present
      when: ansible_facts["os_family"] == "RedHat"


  tasks:
    - name: Install available updates (Debian)
      ansible.builtin.apt:
        upgrade: true
      when: ansible_facts["os_family"] == "Debian"
    
    - name: Install available updates (RH)
      ansible.builtin.dnf:
        name: "*" 
        state: present
      when: ansible_facts["os_family"] == "RedHat"

    - name: Check if reboot is needed (Debian)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_facts["os_family"] == "Debian"

    - name: Check if reboot is needed (RH)
      ansible.builtin.command:
        cmd: needs-restarting
      register: needs_restarting_result

    - name: Reboot if required (Debian)
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists and ansible_facts["os_family"] == "Debian"

    - name: Reboot if required (RH)
      reboot:
      when: needs_restarting_result.rc == 1 and ansible_facts["os_family"] == "RedHat"