---
- hosts: all
  become: true

  pre_tasks:
    - name: Install yum-utils if not installed on RHEL systems.
      ansible.builtin.dnf:
        name: yum-utils
        state: present
      when: ansible_facts["os_family"] == "RedHat"

  tasks:
    - name: Update Debian/Ubuntu
      block:
        - name: DEB -Update apt cache
          ansible.builtin.apt:
            update_cache: true
            cache_valid_time: 3600

        - name: DEB -Install available updates
          ansible.builtin.apt:
            upgrade: true

        - name: DEB - Check if reboot is needed
          ansible.builtin.stat:
            path: /var/run/reboot-required
          register: reboot_required_file

        - name: DEB - Reboot if needed
          ansible.builtin.reboot:
          when: reboot_required_file.stat.exists
      when: ansible_facts["os_family"] == "Debian"


    - name: Update RHEL
      block:
        - name: RH - Update dnf cache
          ansible.builtin.dnf:
            update_cache: true

        - name: RH - Install available updates
          ansible.builtin.dnf:
            name: "*"
            state: latest

        - name: RH - Check if reboot is needed
          ansible.builtin.command:
            cmd: needs-restarting
          register: needs_restarting_result
          changed_when: needs_restarting_result.rc == 1

        - name: RH - Reboot if needed
          ansible.builtin.reboot:
          when: needs_restarting_result.rc == 1
      when: ansible_facts["os_family"] == "RedHat"