---
- name: Install LAMP Stack on Ubuntu 20.04
  become: yes
  become_method: sudo

  tasks:
    - name: Upgrade repos / Install Updates
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install Needed Packages
      apt:
        pkg:
        - apache2
        - mysql-server
        - php
        - libapache2-mod-php
        - php-mysql

...