---
- name: Setup Ubuntu Unifi Controller
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_method: sudo

  tasks:
    - name: Update repos
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Needed Packages
      ansible.builtin.apt:
        pkg:
        - ca-certificates
        - apt-transport-https
    
    - name: Add mongodb repos
      block:
        - name: Add mongodb gpg key
          ansible.builtin.get_url:
            url:
            dest:
        - name: Add mongodb repo
          ansible.builtin.apt_repository:
            repo:
            state: present

    - name: Add Unifi repos
      block:
      - name: Add gpg key
        ansible.builtin.get_url:
          url: "https://dl.ui.com/unifi/unifi-repo.gpg"
          dest: /etc/apt/trusted.gpg.d/unifi-repo.gpg
        
      - name: Add repo
        ansible.builtin.apt_repository:
          repo: 'deb https://www.ui.com/downloads/unifi/debian stable ubiquiti'
          state: present

    - name: Install Unifi Controller
      ansible.builtin.apt:
        update_cache: yes
        name: unifi
        state: present

    - name: Enable Unifi Service
      ansible.builtin.service:
        name: unifi
        state: started
        enabled: true

    - name: Change Hostname
      hostname:
        name: unifi-controller
...