---
- name: Setup Ubuntu Unifi Controller
  hosts: testing
  become: yes
  become_method: sudo

  tasks:
    - name: Upgrade repos / Install Updates
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install Needed Packages
      apt:
        pkg:
        - xe-guest-utilities
        - ca-certificates
        - apt-transport-https
        - openjdk-8-jre-headless

    - name: Add Unifi repos
      ansible.builtin.shell:
        cmd: echo 'deb https://www.ui.com/downloads/unifi/debian stable ubiquiti' | tee /etc/apt/sources.list.d/100-ubnt-unifi.list
    
    - name: Add Unifi GPG keys
      ansible.builtin.shell:
        cmd: apt-key adv --keyserver keyserver.ubuntu.com --recv 06E85760C0A52C50 

    - name: Install Unifi Controller
      apt:
        update_cache: yes
        name: unifi
        state: present
    
    - name: Change Hostname
      hostname:
        name: unifi-controller

...